### ISSUE TITLE
telegram chats duplicate

### ISSUE THREAD

**Issue by REDHAT3** [bots-house/share-file-bot#50]
![Screenshot from 2020-10-30 17-07-14](https://user-images.githubusercontent.com/22527108/97722202-09d04d80-1ad3-11eb-8ac2-cb75d1eb0386.png)

@mr-linch  telegram_id в бд не являеться уникальным полем, по этому мы можем с двух и больше аккаунтов добавлять канал, отпиши или так должно быть или нужно пофиксить

**Comment by mr-linch** [comment]
Это нужно для того чтобы два админа одного канала могли пользоваться ботом, пока мы не реализуем нормальную систему совместной работы.
